# Generated by Django 4.2.17 on 2025-01-11 16:17

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrapbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapbook',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scrapbook',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scrapbook',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Private'), (2, 'Public')], default=1),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Private'), (2, 'Public')], default=-1)),
                ('content', models.TextField(blank=True, max_length=200)),
                ('approved', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_author', to=settings.AUTH_USER_MODEL)),
                ('scrapbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='scrapbook.scrapbook')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('caption', models.TextField(blank=True, max_length=200)),
                ('is_puzzle', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_image', to='scrapbook.post')),
            ],
        ),
    ]
