# Generated by Django 4.2.17 on 2025-01-15 12:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbook', '0004_alter_image_post_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='postimage'),
        ),
    ]
