# Generated by Django 4.2.17 on 2025-01-15 14:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbook', '0005_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapbook',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='scrapbookimage'),
        ),
    ]
