# Generated by Django 4.2.17 on 2025-01-15 19:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbook', '0006_scrapbook_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='post_image'),
        ),
        migrations.AlterField(
            model_name='scrapbook',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='scrapbook_image'),
        ),
    ]
