# Generated by Django 4.2.17 on 2025-01-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbook', '0012_alter_sharedaccess_shared_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Private'), (2, 'Public')], default=0),
        ),
    ]
